// featured.js
window.paradiseEvents = {
    creation: [
        { title: "The Beginning of Creation", text: 'Jehovah created Adam and Eve in his image, perfect and with free will, to live in the Garden of Eden forever. Genesis 1:27-28 states, “God created man in his image... and said to them: ‘Be fruitful and become many.’”' },
        { title: "The Earth Prepared", text: 'Jehovah formed the earth to be inhabited, with perfect ecosystems for life. Isaiah 45:18 says, “Jehovah... did not create [the earth] simply for nothing, but formed it to be inhabited.”' },
        { title: "Creation of Animals", text: 'Jehovah filled the earth with diverse creatures, each according to its kind, showcasing his wisdom. Genesis 1:24 states, “Let the earth bring forth living creatures according to their kinds.”' },
        { title: "The Garden of Eden", text: 'Jehovah planted Eden as a paradise home for humanity, with abundant resources. Genesis 2:8 says, “Jehovah God planted a garden in Eden, and there he put the man.”' },
        { title: "The Tree of Knowledge", text: 'Jehovah set a test of obedience with the tree of knowledge, respecting free will. Genesis 2:17 warns, “You must not eat from it, for in the day you eat from it you will die.”' },
        { title: "Adam’s Role", text: 'Adam was tasked with naming animals and caring for Eden, reflecting Jehovah’s trust. Genesis 2:19 says, “Jehovah God... brought them to the man to see what he would call them.”' },
        { title: "Eve’s Creation", text: 'Jehovah created Eve as Adam’s complement, establishing marriage. Genesis 2:22 states, “Jehovah God built the rib... into a woman and brought her to the man.”' },
        { title: "Perfect Harmony", text: 'Adam and Eve lived in harmony with Jehovah, free from pain or death. Psalm 145:16 says, “You open your hand and satisfy the desire of every living thing.”' }
    ],
    prophecy: [
        { title: "The First Prophecy", text: 'After sin, Jehovah promised a seed to crush the serpent, foretelling redemption. Genesis 3:15 says, “I will put enmity between you and the woman, and between your offspring and her offspring.”' },
        { title: "Covenant with Noah", text: 'Jehovah promised never again to destroy the earth with a flood, showing mercy. Genesis 9:11 states, “Never again will all flesh be destroyed by the waters of a flood.”' },
        { title: "Abraham’s Covenant", text: 'Jehovah promised Abraham a seed to bless all nations, pointing to the Messiah. Genesis 22:18 says, “By means of your offspring all nations of the earth will be blessed.”' },
        { title: "The Law Covenant", text: 'Through Moses, Jehovah gave Israel the Law, preparing them for the Messiah. Exodus 19:5 states, “If you will strictly obey my voice... you will become my special property.”' },
        { title: "David’s Kingdom", text: 'Jehovah promised David an everlasting throne, fulfilled through Christ. 2 Samuel 7:16 says, “Your house and your kingdom will be secure forever before me.”' },
        { title: "Prophecy of Babylon", text: 'Jehovah foretold Judah’s exile and return, proving his sovereignty. Jeremiah 25:11 states, “This whole land will become a desolate ruin, and these nations will serve the king of Babylon.”' },
        { title: "Messiah’s Arrival", text: 'Daniel’s prophecy pinpointed the Messiah’s coming, fulfilled by Jesus. Daniel 9:25 says, “From the issuing of the word to restore... until Messiah the Leader, there will be seven weeks and sixty-two weeks.”' },
        { title: "The Suffering Servant", text: 'Isaiah foretold the Messiah’s suffering to redeem humanity. Isaiah 53:5 says, “He was pierced for our transgression... and by his wounds we are healed.”' }
    ],
    sacrifice: [
        { title: "Jesus’ Birth", text: 'Jesus, the promised seed, was born in Bethlehem to save humanity. Micah 5:2 states, “From you, O Bethlehem Ephrathah... will come out one to be ruler in Israel.”' },
        { title: "Jesus’ Baptism", text: 'Jesus’ baptism marked him as the Messiah, anointed by Jehovah. Matthew 3:17 says, “This is my Son, the beloved, whom I have approved.”' },
        { title: "Ministry Begins", text: 'Jesus preached the Kingdom, offering hope to all. Matthew 4:17 states, “From that time on, Jesus began preaching: ‘Repent, for the Kingdom of the heavens has drawn near.’”' },
        { title: "Miracles of Jesus", text: 'Jesus’ miracles, like healing and raising the dead, proved his divine authority. John 20:30 says, “Jesus performed many other signs... which are not written in this book.”' },
        { title: "Sermon on the Mount", text: 'Jesus taught principles of love and faith, guiding true worship. Matthew 5:3 says, “Happy are those conscious of their spiritual need, since the Kingdom of the heavens belongs to them.”' },
        { title: "The New Covenant", text: 'Jesus established the new covenant for salvation, open to all. Luke 22:20 says, “This cup means the new covenant by virtue of my blood, which is to be poured out.”' },
        { title: "Jesus’ Sacrifice", text: 'Jesus’ death provided the ransom for humanity’s sins. Matthew 20:28 says, “The Son of man came... to give his life as a ransom for many.”' },
        { title: "The Resurrection", text: 'Jesus’ resurrection confirmed his role as King, defeating death. Acts 2:32 says, “This Jesus God resurrected, of which fact we are all witnesses.”' }
    ],
    paradise: [
        { title: "The New Covenant Established", text: 'At the Memorial in 33 C.E., Jesus instituted the New Covenant, offering his life as a ransom. Luke 22:20 states, “This cup means the new covenant by virtue of my blood, which is to be poured out.” This replaced the Law Covenant with Israel, opening salvation to all faithful ones, as Hebrews 8:13 confirms, “In saying ‘a new covenant,’ he has made the first one obsolete.”' },
        { title: "The Memorial’s Significance", text: 'The Memorial commemorates Jesus’ sacrifice, observed annually by Jehovah’s servants. 1 Corinthians 11:24-25 instructs, “Keep doing this in remembrance of me.” It symbolizes the New Covenant’s promise, uniting anointed Christians and the great crowd in worship, fulfilling Jesus’ command to remember his death until he returns, as per 1 Corinthians 11:26.' },
        { title: "Replacement of the 12 Tribes", text: 'The original 12 tribes of Israel were replaced by a spiritual Israel, the 144,000, chosen from all nations. Revelation 7:4-8 lists these sealed ones, and Galatians 6:16 calls them “the Israel of God.” This fulfills God’s promise to Abraham through a faithful remnant, as Romans 11:26 states, “All Israel will be saved,” now through the anointed.' },
        { title: "The 144,000’s Heavenly Calling", text: 'The 144,000, symbolized by the 12 tribes, are anointed with holy spirit to rule with Christ. Revelation 14:1-3 describes them as “bought from the earth” to stand with the Lamb, fulfilling Jesus’ promise in Luke 22:29, “I make a covenant with you, just as my Father has made a covenant with me, for a kingdom.”' },
        { title: "The Great Crowd’s Earthly Hope", text: 'The great crowd, a vast multitude from all nations, will survive Armageddon to live on earth. Revelation 7:9-10 portrays them, “a great crowd... standing before the throne,” relying on the 144,000’s priestly service to mediate Jesus’ ransom. Their presence highlights the need for the 144,000 to assist Jesus in guiding and teaching during the restoration, as Revelation 7:15 states, “They are rendering him sacred service day and night.”' },
        { title: "The Great Tribulation Begins", text: 'A time of unprecedented distress signals the end, preparing for Christ’s rule with the 144,000. Matthew 24:21 warns, “There will be great tribulation such as has not occurred since the world’s beginning.” This purifies the earth, enabling the 144,000 to support Jesus in judging and preserving the great crowd, as Revelation 7:14 notes, “They have washed their robes and made them white in the blood of the Lamb.”' },
        { title: "The Millennial Reign with Christ", text: 'During the 1,000-year reign, the 144,000 rule as kings and priests with Christ, aiding the great crowd’s perfection. Revelation 20:6 promises, “They will be priests of God and of the Christ and will rule as kings with him for the 1,000 years.” The 144,000’s role is crucial to teach and guide the great crowd, fulfilling the Davidic Kingdom’s restoration, as Psalm 110:2 states, “Rule in the midst of your enemies.”' },
        { title: "Satan’s Final Defeat and Kingdom Returned", text: 'After the Millennium, Satan’s last rebellion is crushed, and the Kingdom is handed back to Jehovah. Revelation 20:10 says, “The Devil... will be hurled into the lake of fire,” and 1 Corinthians 15:24 declares, “He hands over the Kingdom to his God and Father.” The 144,000’s work with the great crowd completes, restoring paradise under Jehovah’s direct rule, as Psalm 37:29 affirms, “The righteous will possess the earth, and they will live forever on it.”' }
    ]
};

window.featuredEvents = [
    { title: "God or Government?", text: 'Human governments promise security but often lead to oppression and failure, as Psalm 146:3 warns, “Do not put your trust in princes, in whom there is no salvation.” Jehovah’s Kingdom offers eternal peace, fulfilling Daniel 2:44, “The God of heaven will set up a kingdom that will never be destroyed.” Choose Jehovah’s perfect rule over flawed human systems for lasting hope.' },
    { title: "Spirituality or Wealth?", text: 'Chasing wealth breeds anxiety and emptiness, as Ecclesiastes 5:10 states, “A lover of silver will never be satisfied with silver.” Cultivating spirituality brings contentment, as 1 Timothy 6:6 affirms, “Godly devotion along with contentment is great gain.” Choose spiritual riches that endure over fleeting material wealth.' },
    { title: "Morality or Immorality?", text: 'Immorality destroys relationships and self-respect, as Proverbs 6:32 says, “Anyone committing adultery lacks good sense; he who does so destroys himself.” Living by Jehovah’s moral standards fosters dignity and peace, per Psalm 119:165, “Abundant peace belongs to those who love your law.” Choose morality to gain Jehovah’s approval and lasting joy.' },
    { title: "Hope or Hopelessness?", text: 'Worldly pursuits lead to despair, as Ecclesiastes 1:14 observes, “Everything under the sun is vanity and a chasing after the wind.” Jehovah’s promises give enduring hope, as Romans 15:13 declares, “May the God who gives hope fill you with all joy and peace.” Choose Jehovah’s hope to find purpose and strength.' },
    { title: "Sobriety or Drugs?", text: 'Drugs enslave and cloud the mind, as Proverbs 20:1 warns, “Wine is a ridiculer, alcohol is unruly.” Sobriety honors Jehovah, as 1 Peter 5:8 urges, “Keep your senses, be watchful.” Choose a clear mind to serve God faithfully and live with strength.' },
    { title: "Worship or Partying?", text: 'Partying often leads to excess and spiritual emptiness, as Galatians 5:21 lists “wild parties” among “works of the flesh.” Worshiping Jehovah brings true joy, as Psalm 16:11 states, “In your presence is abundant joy.” Choose worship to find fulfillment in serving God.' },
    { title: "Truth or Deception?", text: 'Lies blind us to reality, as John 8:44 calls Satan “the father of the lie.” Jehovah’s truth lights the way, as John 17:17 declares, “Your word is truth.” Choose truth to walk in God’s light and avoid the darkness of deception.' },
    { title: "Purpose or Aimlessness?", text: 'Worldly goals leave us lost, as Ecclesiastes 2:11 says, “I saw that everything was vanity.” Serving Jehovah gives clear direction, as Ecclesiastes 12:13 concludes, “Fear the true God and keep his commandments, for this is the whole obligation of man.” Choose purpose through devotion to God.' }
];

window.spotlightEvents = {
    inspired: [
        { title: "Historical Support", text: 'The Bible’s historical accuracy is confirmed by extensive archaeological evidence, such as the Tel Dan Stele, which corroborates 2 Samuel 8:13, “David made a name when he struck down the Edomites.” The Lachish Letters align with Jeremiah 34:7, detailing Judah’s defense against Babylon. These findings affirm the Bible’s reliability as a historical record, proving its accounts are not myths but grounded in reality, as Psalm 119:160 declares, “The very essence of your word is truth.” This precision reflects Jehovah’s oversight in preserving His Word, as Isaiah 46:10 states, “My purpose will take effect, and I will carry out all that I please.”' },
        { title: "Scientific Evidence", text: 'The Bible aligns with scientific truths, written long before modern discoveries. Isaiah 40:22 describes the earth as a circle, “He stretches out the heavens like a fine gauze,” suggesting its spherical nature and the universe’s expansion. Job 26:7 notes, “He stretches out the northern sky over empty space, suspending the earth upon nothing,” reflecting an understanding of the earth’s position in space. These statements, penned centuries ago, demonstrate divine insight, as 2 Timothy 3:16 affirms, “All Scripture is inspired of God,” revealing Jehovah’s wisdom beyond human knowledge.' },
        { title: "Manuscript Survivability", text: 'The Bible’s text has been preserved through thousands of ancient manuscripts, such as the Dead Sea Scrolls, which confirm the accuracy of modern translations. Over 5,000 Greek manuscripts of the New Testament exist, far surpassing other ancient texts. This preservation fulfills Isaiah 40:8, “The word of our God endures forever,” proving Jehovah’s ability to protect His message across millennia.' },
        { title: "Prophetic Accuracy", text: 'The Bible’s prophecies, like the fall of Babylon in Isaiah 13:19-20, were fulfilled precisely when Cyrus conquered it in 539 B.C.E., as Daniel 5:30 records. Such accuracy, spanning centuries, shows divine inspiration, as 2 Peter 1:21 states, “Prophecy was at no time brought by man’s will, but men spoke from God as they were moved by holy spirit.”' },
        { title: "Moral Superiority", text: 'The Bible’s principles, like the Golden Rule in Matthew 7:12, “All things that you want men to do to you, you also must do to them,” provide a timeless moral framework. Its laws on justice, love, and mercy surpass human philosophies, as Psalm 19:7 declares, “The law of Jehovah is perfect, restoring the soul.”' },
        { title: "Transformative Power", text: 'The Bible changes lives, turning sinners into saints, as seen in 1 Corinthians 6:11, “That is what some of you were. But you have been washed clean.” Its teachings inspire love, forgiveness, and hope, fulfilling Hebrews 4:12, “The word of God is alive and exerts power.”' },
        { title: "Unity of Message", text: 'Despite 40 writers over 1,600 years, the Bible maintains a unified theme of God’s Kingdom. From Genesis to Revelation, it consistently points to Jehovah’s purpose, as Revelation 21:4 promises, “Death will be no more.” This coherence confirms its divine origin, as 2 Timothy 3:16 states.' },
        { title: "Endurance Through Opposition", text: 'Despite bans and burnings, the Bible has survived, fulfilling Jesus’ words in Matthew 24:35, “Heaven and earth will pass away, but my words will by no means pass away.” Its resilience proves Jehovah’s protection, as Psalm 119:89 declares, “Your word, O Jehovah, endures forever.”' }
    ],
    translated: [
        { title: "The Septuagint", text: 'The Greek Septuagint, completed around 200 B.C.E., translated the Hebrew Scriptures, making them accessible to Greek-speaking Jews. Its accuracy is evident in its alignment with the Dead Sea Scrolls, supporting the reliability of texts like Isaiah 7:14, foretelling the Messiah’s birth.' },
        { title: "The Latin Vulgate", text: 'Jerome’s Latin Vulgate, completed in 405 C.E., became the standard Bible for centuries. Its careful translation preserved key doctrines, like John 1:1, “The Word was with God, and the Word was a god,” maintaining the original Greek’s nuance.' },
        { title: "Early English Bibles", text: 'Translators like Tyndale risked death to render the Bible into English, with works like the 1535 Tyndale Bible. His translation of Psalm 23:1, “The Lord is my shepherd,” set a standard for clarity, influencing later versions like the King James.' },
        { title: "The King James Version", text: 'The 1611 King James Bible, based on Hebrew and Greek texts, became a literary masterpiece. Its rendering of Psalm 83:18, “That men may know that thou, whose name alone is JEHOVAH,” restored God’s name, aligning with the Hebrew Tetragrammaton.' },
        { title: "Modern Translations", text: 'Modern Bibles, like the New World Translation, prioritize accuracy to original texts. Its restoration of “Jehovah” in over 7,000 places, as in Exodus 3:15, ensures fidelity to the Hebrew, fulfilling the command to “make known his name.”' },
        { title: "The Dead Sea Scrolls", text: 'Discovered in 1947, the Dead Sea Scrolls confirmed the Hebrew text’s accuracy. The Great Isaiah Scroll, nearly identical to modern texts, supports Isaiah 40:8, “The word of our God endures forever,” proving divine preservation.' },
        { title: "New World Translation", text: 'The New World Translation, first released in 1950, emphasizes linguistic precision. Its rendering of John 17:3, “Taking in knowledge of you, the only true God,” reflects the Greek accurately, aiding millions in understanding Jehovah’s truth.' },
        { title: "Digital Accessibility", text: 'Today’s digital Bibles, like the JW Library app, make Scriptures available in over 1,000 languages. This fulfills Matthew 24:14, “This good news of the Kingdom will be preached in all the inhabited earth,” ensuring global access to God’s Word.' }
    ],
    organized: [
        { title: "Early Christian Congregations", text: 'First-century Christians organized under apostles’ guidance, as Acts 14:23 shows, “They appointed elders in every congregation.” This structure ensured unity, fulfilling Jesus’ prayer in John 17:21, “That they may all be one.”' },
        { title: "The Great Apostasy", text: 'After the apostles, false teachings infiltrated, as Acts 20:29 warned, “Oppressive wolves will enter in among you.” This apostasy corrupted worship, but Jehovah preserved a remnant, as Romans 11:5 states, “There has come to be a remnant.”' },
        { title: "The Reformation", text: 'The 16th-century Reformation challenged false doctrines, with men like Luther emphasizing Scripture. Yet, incomplete reforms left errors, as 2 Timothy 4:3 warns, “They will not put up with the healthful teaching.”' },
        { title: "Bible Students Emerge", text: 'In the 1870s, Charles Taze Russell’s Bible Students studied Scriptures diligently, restoring truths like Jehovah’s name. Their work aligned with Malachi 3:16, “Those in fear of Jehovah spoke with one another, and Jehovah listened.”' },
        { title: "Jehovah’s Witnesses Named", text: 'In 1931, the Bible Students adopted the name Jehovah’s Witnesses, based on Isaiah 43:10, “You are my witnesses,” declares Jehovah. This marked their global mission to proclaim God’s Kingdom.' },
        { title: "Global Organization", text: 'Jehovah’s Witnesses grew into a unified global brotherhood, with nearly 10 million members today. Acts 15:14 says, “God turned his attention to the nations to take out of them a people for his name,” fulfilled through their organization.' },
        { title: "Governing Body", text: 'The Governing Body, modeled after Acts 15:2, leads Jehovah’s Witnesses, ensuring doctrinal unity. Their guidance fulfills Matthew 24:45, “Who really is the faithful and discreet slave whom his master appointed?”' },
        { title: "Kingdom Halls", text: 'Kingdom Halls worldwide provide places for worship and Bible study, reflecting Psalm 122:1, “I rejoiced when they said to me: ‘Let us go to the house of Jehovah.’” This supports organized worship globally.' }
    ],
    restored: [
        { title: "Restoring True Worship", text: 'Jehovah’s Witnesses restored pure worship by rejecting pagan traditions, as 2 Corinthians 6:17 urges, “Separate yourselves, says Jehovah, and quit touching the unclean thing.” Their focus on Bible truth fulfills Malachi 3:18, distinguishing true worshipers.' },
        { title: "Preaching the Kingdom", text: 'Jehovah’s Witnesses preach globally, fulfilling Matthew 24:14, “This good news of the Kingdom will be preached in all the inhabited earth.” Their door-to-door ministry emulates Jesus’ example in Luke 8:1.' },
        { title: "Rejecting False Doctrines", text: 'By rejecting teachings like the Trinity and hellfire, Jehovah’s Witnesses uphold John 4:23, “True worshippers will worship the Father with spirit and truth.” This restores worship to its biblical roots.' },
        { title: "Neutrality in Politics", text: 'Jehovah’s Witnesses remain neutral, as Jesus taught in John 17:16, “They are no part of the world.” This stance aligns with their loyalty to Jehovah’s Kingdom, per Daniel 2:44.' },
        { title: "Love Among Themselves", text: 'Their global brotherhood reflects John 13:35, “By this all will know that you are my disciples—if you have love among yourselves.” This love unites millions across nations.' },
        { title: "Education Through Publications", text: 'Publications like The Watchtower teach Bible truths, fulfilling Habakkuk 2:2, “Write down the vision... so that the one reading it aloud may do so fluently.” These aid millions in studying Scripture.' },
        { title: "Annual Conventions", text: 'Conventions strengthen faith, as Hebrews 10:24-25 urges, “Let us consider one another to incite to love and fine works, not forsaking our meeting together.” These gatherings unite worshipers globally.' },
        { title: "Paradise Restored", text: 'Jehovah’s Witnesses prepare for paradise, as Revelation 21:4 promises, “Death will be no more, neither will mourning nor outcry nor pain be anymore.” Their work heralds the restoration of Jehovah’s original purpose.' }
    ]
};
