const launch = [
    {
        T: "Pure Worship",
        S: [
            "James 1:27 - The form of worship that is clean and undefiled from the standpoint of our God and Father is this: to look after orphans and widows in their tribulation and to keep oneself without spot from the world."
        ],
        D: "Exploring what constitutes pure worship in Jehovah’s eyes and how to apply these principles in daily life."
    },
    {
        T: "Accuracy",
        S: [
            "Psalm 119:160 - The sum of your word is truth and every one of your righteous judgments endures forever."
        ],
        D: `
            <p>The Bible’s accurate teachings form the foundation of true worship guiding Jehovah’s Witnesses to honor Jehovah follow Jesus and prepare for His Kingdom. These truths proven by Scripture and practice lead to everlasting life.</p>
            <br><p><strong>Jehovah the Only True God</strong></p><p>Jehovah is the only true God identified by His name as Psalm 83:18 declares. Jesus His Son is subordinate sent to reveal Jehovah’s will (John 3:16). Unlike false gods Jehovah’s sovereignty is proven by His creation and prophecies. Jehovah’s Witnesses honor His name in 240+ lands distinguishing true worship from idolatry.</p><p><em>“That men may know that you whose name is Jehovah you alone are the Most High over all the earth.” — Psalm 83:18</em></p>
            <br><p><strong>Holy Spirit as God’s Active Force</strong></p><p>The Holy Spirit is Jehovah’s active force not a person used to inspire prophets and empower disciples (Acts 2:17). Unlike false views of a triune God Scripture shows it as God’s power like wind or fire guiding true worshipers. Jehovah’s Witnesses rely on this force to preach and live morally.</p><p><em>“I will pour out my spirit on all sorts of flesh and your sons and daughters will prophesy.” — Acts 2:17</em></p>
            <br><p><strong>God’s Kingdom and Its Rulers</strong></p><p>God’s Kingdom a heavenly government will restore earth under Christ (Daniel 2:44). The New Covenant selects 144000 anointed ones to rule as kings and priests (Luke 22:20; Revelation 14:1). This hope fulfilled since 1914 drives true worshipers to preach unlike human governments that fail.</p><p><em>“The God of heaven will set up a kingdom that will never be destroyed.” — Daniel 2:44</em></p>
            <br><p><strong>Death and Resurrection</strong></p><p>The dead are unconscious awaiting resurrection (Ecclesiastes 9:5). Jehovah’s Kingdom will resurrect billions to earth or heaven (John 5:28-29). Unlike false afterlife myths this truth comforts true worshipers as Jehovah’s Witnesses teach globally offering hope based on God’s justice.</p><p><em>“Do not be amazed at this for the hour is coming in which all those in the memorial tombs will hear his voice and come out.” — John 5:28-29</em></p>
            <br><p><strong>Free Will and Moral Living</strong></p><p>Jehovah grants free will allowing humans to choose obedience (Deuteronomy 30:19). True worshipers like Jehovah’s Witnesses live simply avoiding materialism (1 Timothy 6:8). This contrasts with false teachings of fate or greed as the Bible’s moral guidance promotes peace and health.</p><p><em>“I have put life and death before you... choose life.” — Deuteronomy 30:19</em></p>
            <br><p><strong>Memorial of Christ’s Death</strong></p><p>Jehovah’s Witnesses commemorate Jesus’ death annually on Nisan 14 following his command (1 Corinthians 11:24). This simple ceremony—bread wine prayers—honors his ransom unlike pagan festivals. In 2024 over 20 million attended globally proving true worship’s devotion to Christ.</p><p><em>“Keep doing this in remembrance of me.” — 1 Corinthians 11:24</em></p>
            <br><p><strong>Global Preaching and Unity</strong></p><p>True worshipers preach the Kingdom globally (Matthew 24:14) as Jehovah’s Witnesses do in 1000+ languages. Their unity with identical beliefs in 120000 congregations reflects God’s spirit (Psalm 133:1). Unlike divided religions this accuracy shows Jehovah’s blessing on true worship.</p><p><em>“This good news of the Kingdom will be preached in all the inhabited earth.” — Matthew 24:14</em></p>
            <br><p><strong>Bible’s Reliability and Discipline</strong></p><p>The Bible’s accuracy—scientific (Isaiah 40:22) historical (2 Kings 20:20) prophetic (Ezekiel 26:12)—guides true worship (Psalm 119:160). Baptism follows dedicated study (Acts 8:36) and discipline keeps congregations clean (1 Corinthians 5:13). Jehovah’s Witnesses uphold these truths unlike false religions.</p>
        `
    },
    {
        T: "Blasphemy",
        S: [
            "Isaiah 42:8 - I am Jehovah, that is my name; I give my glory to no one else."
        ],
        D: `
            <p>False teachings blaspheme Jehovah’s sovereignty, spreading lies that mislead billions with pagan rituals and doctrines. True worshipers reject these deceptions to honor Jehovah purely, avoiding the spiritual harm of false worship.</p>
            <br><p><strong>Trinity and False Gods</strong></p><p>The Trinity doctrine, formalized at Nicaea (325 CE), falsely claims Jehovah, Jesus, and the Holy Spirit are one God, mimicking Babylonian triads (2000 BCE). Scripture declares one true God (1 Corinthians 8:6). This lie blasphemes Jehovah’s unique sovereignty, misleading billions in false worship.</p><p><em>“There is actually to us one God, the Father, from whom all things are.” — 1 Corinthians 8:6</em></p>
            <br><p><strong>Hellfire and Immortal Soul</strong></p><p>Hellfire, rooted in Greek Hades (800 BCE), claims eternal torment, and the immortal soul myth, from Egyptian ka beliefs (3000 BCE), denies death’s unconsciousness (Psalm 146:4). These lies misrepresent Jehovah’s justice, scaring people from true worship, unlike the Bible’s resurrection hope.</p><p><em>“His spirit goes out, he returns to the ground; on that very day his thoughts perish.” — Psalm 146:4</em></p>
            <br><p><strong>Karma and Fate</strong></p><p>Karma, from Hindu Vedas (1500 BCE), claims cosmic reward/punishment, and fate, from Chaldean astrology (2000 BCE), denies free will. Both contradict Jehovah’s gift of choice (Joshua 24:15). These lies blaspheme His sovereignty, trapping people in false destinies.</p><p><em>“Choose for yourselves today whom you will serve.” — Joshua 24:15</em></p>
            <br><p><strong>Christmas and Easter</strong></p><p>Christmas, tied to Roman Saturnalia (200 BCE), honors sun gods with trees and lights, and Easter, from Saxon Eostre (700 CE), uses fertility symbols (eggs, rabbits). These pagan festivals (Isaiah 42:8) blaspheme Jehovah by blending idolatry with Jesus’ name, unlike true worship’s simplicity.</p><p><em>“I am Jehovah, that is my name; I give my glory to no one else.” — Isaiah 42:8</em></p>
            <br><p><strong>Birthdays and Astrology</strong></p><p>Birthdays, linked to Egyptian pharaoh cults (2600 BCE), glorify self, and astrology, from Chaldean star charts (2000 BCE), predicts fate (Deuteronomy 18:10). These practices blaspheme Jehovah’s purpose (Psalm 36:9), diverting worshipers from His truth with pagan rituals.</p><p><em>“With you is the source of life; by your light we see light.” — Psalm 36:9</em></p>
            <br><p><strong>Prosperity Gospel and Clergy Hypocrisy</strong></p><p>The prosperity gospel, from 1900s televangelists, falsely promises wealth as God’s will (Matthew 6:24), and hypocritical clergy, like Pharisees, preach but live immorally (Matthew 23:3). These lies exploit followers, blaspheming Jehovah’s generosity and justice.</p><p><em>“You cannot slave for God and for Riches.” — Matthew 6:24</em></p>
            <br><p><strong>Evolution and Interfaith Compromise</strong></p><p>Evolution, from Darwin (1859), denies Jehovah’s creation (Genesis 1:27), and interfaith movements, since the 20th century, equate false gods with Jehovah (Deuteronomy 4:39). These lies blaspheme His role as Creator and sovereign, misleading people from true worship.</p><p><em>“God created man in his image.” — Genesis 1:27</em></p>
            <br><p><strong>Non-Biblical Books and Ancestor Worship</strong></p><p>Non-biblical texts like the Quran or Vedas (Psalm 119:105), ancestor worship in Voodoo (Isaiah 8:19), and the cross symbol from Tammuz cults (Deuteronomy 4:16) contradict Scripture. These lies blaspheme Jehovah’s truth, promoting idolatry over pure worship.</p><p><em>“Your word is a lamp to my foot and a light to my path.” — Psalm 119:105</em></p>
        `
    },
{
    T: "Discernment",
    S: [
        "Hebrews 5:14 - Solid food belongs to mature people, to those who through use have their powers of discernment trained to distinguish both right and wrong."
    ],
    D: `
        <p>Discernment is the spiritual skill to distinguish true worship, approved by Jehovah, from false worship promoted by Satan. Through Bible study, prayer, and careful observation, Jehovah’s Witnesses develop this ability to navigate deception and honor Jehovah purely, preparing for everlasting life in His Kingdom.</p>
        <br><p><strong>Testing Teachings with Scripture</strong></p><p>Discernment begins by comparing every teaching to the Bible, as the Bereans did when they “examined the Scriptures daily” to verify Paul’s message. A teaching must align with Jehovah’s sovereignty and Jesus’ role as the truth. For example, does it uphold Jehovah as the only true God, or does it add human rules? True worship relies on Scripture alone, while false worship introduces traditions or philosophies that contradict God’s Word. To grow in discernment, study the Bible regularly to ensure your beliefs match its clear standards.</p><p><em>“They examined the Scriptures daily to see whether these things were so.” — Acts 17:11</em></p>
        <br><p><strong>Recognizing Jehovah’s Name</strong></p><p>True worship centers on Jehovah’s name, which He declared as His memorial forever. Discernment involves checking if a religion boldly uses “Jehovah” in its teachings and prayers, as Jesus did when teaching his followers. Many religions replace Jehovah’s name with titles like “Lord” or “God,” obscuring His identity. This is a key sign of false worship. To sharpen discernment, notice whether a faith honors Jehovah’s name in its publications, songs, and preaching, reflecting its commitment to true worship.</p><p><em>“This is my name forever, and this is how I am to be remembered.” — Exodus 3:15</em></p>
        <br><p><strong>Spotting Pagan Influences</strong></p><p>Discernment helps identify pagan influences in worship, which Jehovah commands His people to avoid. Look for rituals, symbols, or festivals not found in the Bible, such as those tied to ancient idol worship. For example, does a religion use images or celebrate holidays with roots outside Scripture? True worship, as practiced by Jehovah’s Witnesses, remains free of such traditions, relying solely on God’s Word. To develop this skill, research the origins of religious practices and compare them to Jehovah’s standards for pure worship.</p><p><em>“Get out from among them, and separate yourselves, says Jehovah, and quit touching the unclean thing.” — 2 Corinthians 6:17</em></p>
        <br><p><strong>Evaluating Global Unity</strong></p><p>True worshipers are united worldwide, sharing the same beliefs and practices, as Jehovah desires. Discernment involves evaluating whether a religion demonstrates this unity across nations or is divided by conflicting doctrines. Jehovah’s Witnesses, for example, teach the same Bible truths in every country, reflecting God’s spirit. In contrast, false worship often shows division, with differing beliefs or practices. To grow in discernment, observe a religion’s consistency in its teachings and love among its members.</p><p><em>“How good and how pleasant it is for brothers to dwell together in unity!” — Psalm 133:1</em></p>
        <br><p><strong>Strengthening Discernment Through Study</strong></p><p>Regular Bible study sharpens discernment, training worshipers to distinguish right from wrong. By using tools like the New World Translation and Watchtower Library, Jehovah’s Witnesses verify teachings against Scripture, building spiritual maturity. False worship relies on human traditions or vague ideas, but true worshipers study diligently to understand Jehovah’s will. To develop this skill, set aside time daily to read the Bible, reflect on its principles, and discuss its truths with others, ensuring your faith rests on solid truth.</p><p><em>“Solid food belongs to mature people, to those who through use have their powers of discernment trained to distinguish both right and wrong.” — Hebrews 5:14</em></p>
        <br><p><strong>Praying for Wisdom</strong></p><p>Discernment grows through heartfelt prayer to Jehovah, asking for wisdom to see truth clearly. Jesus set the example by praying for guidance during trials, relying on his Father’s direction. When faced with religious claims, pray to understand whether they align with Jehovah’s purpose. False worship lacks this reliance on God, but true worshipers trust Jehovah to guide them. To strengthen discernment, pray regularly, especially when making spiritual decisions, and trust Jehovah to reveal the right path.</p><p><em>“If any one of you is lacking in wisdom, let him keep asking God, for he gives generously to all.” — James 1:5</em></p>
        <br><p><strong>Observing Fruits of Worship</strong></p><p>Discernment involves examining a religion’s fruits, or results, to see if they reflect Jehovah’s blessing. Jesus taught that true worshipers produce good fruits, such as love, peace, and obedience to God’s commands. For example, Jehovah’s Witnesses show love through their global preaching and neutrality in conflicts. Religions marked by greed, division, or violence reveal false worship. To sharpen this skill, look at a faith’s actions—does it promote Jehovah’s standards or worldly values?</p><p><em>“By their fruits you will recognize them.” — Matthew 7:16</em></p>
        <br><p><strong>Choosing the Narrow Path</strong></p><p>Discernment leads to the “narrow” path of true worship, which Jesus said few find. This path involves obeying Jehovah’s commands and rejecting popular but false religions. Check if a faith follows Jesus’ example of loyalty to Jehovah alone, as Jehovah’s Witnesses do by prioritizing Scripture over human traditions. False worship often appeals to the masses but leads to destruction. To develop discernment, choose beliefs that align with the Bible’s truth, even if they require sacrifice, for they lead to everlasting life.</p><p><em>“Go in through the narrow gate, because broad is the gate and spacious is the road leading to destruction.” — Matthew 7:13</em></p>
    `
},
{
    T: "Endurance",
    S: [
        "1 Corinthians 3:6, 7 - I planted, Apollos watered, but God kept making it grow, so that neither the one who plants nor the one who waters is anything, but God who makes it grow."
    ],
    D: `
        <p>Through endurance, Jehovah’s Witnesses faithfully share Bible truths, trusting in God’s power to make their efforts grow, as they teach about His Kingdom and its blessings for mankind.</p>
        <br><p><strong>Current Events Signal Change</strong></p><p>Current events and attitudes indicate a change is near, with wars, food shortages, earthquakes, and moral decline fulfilling Bible prophecy (Matthew 24:3, 7, 8; Luke 21:10, 11; 2 Timothy 3:1-5). These are signs of the last days, urging endurance in preaching Jehovah’s Kingdom as the solution.</p><p><em>“For nation will rise against nation and kingdom against kingdom, and there will be food shortages and earthquakes in one place after another.” — Matthew 24:7, 8</em></p>
        <br><p><strong>Earth Will Never Be Destroyed</strong></p><p>The earth will never be destroyed, as Jehovah established it to remain forever (Psalm 104:5; Ecclesiastes 1:4). True worshipers endure in teaching this hope, trusting in God’s promise for a lasting home for the righteous.</p><p><em>“He has established the earth on its foundations; it will not be moved from its place forever and ever.” — Psalm 104:5</em></p>
        <br><p><strong>Earth’s Environment Restored</strong></p><p>The earth’s environment will be restored to paradise conditions under God’s Kingdom (Isaiah 35:1, 2; Revelation 11:18). Jehovah’s Witnesses endure in sharing this promise of a renewed earth, free from ruin and filled with beauty.</p><p><em>“The wilderness and the waterless region will exult, and the desert plain will be joyful and blossom as the saffron.” — Isaiah 35:1, 2</em></p>
        <br><p><strong>Perfect Health for All</strong></p><p>Everyone will enjoy perfect health under God’s Kingdom, with no sickness or disability (Isaiah 33:24; 35:5, 6). This hope motivates endurance in teaching about Jehovah’s provision for eternal well-being.</p><p><em>“And no resident will say: ‘I am sick.’ The people dwelling in the land will be pardoned for their error.” — Isaiah 33:24</em></p>
        <br><p><strong>Live Forever on Earth</strong></p><p>The righteous will live forever on a paradise earth, inheriting it as God’s gift (Psalm 37:29; Matthew 5:5). Endurance in preaching this truth prepares people for everlasting life under Jehovah’s rule.</p><p><em>“The righteous will possess the earth, and they will live forever on it.” — Psalm 37:29</em></p>
        <br><p><strong>Husbands Love Your Wives</strong></p><p>A husband should love his wife as himself, fostering a strong family bond (Ephesians 5:33; Colossians 3:19). Jehovah’s Witnesses endure in teaching biblical family values that honor Jehovah’s arrangement for marriage.</p><p><em>“Each one of you must love his wife as he does himself.” — Ephesians 5:33</em></p>
        <br><p><strong>Wives Respect Your Husbands</strong></p><p>A wife should deeply respect her husband, supporting the family’s spiritual unity (Ephesians 5:33; Colossians 3:18). Endurance in upholding this principle strengthens marriages in harmony with Jehovah’s will.</p><p><em>“You wives, be in subjection to your husbands, as it is becoming in the Lord.” — Colossians 3:18</em></p>
        <br><p><strong>Loyalty in Marriage</strong></p><p>A husband and wife should be loyal to each other, honoring Jehovah’s view of marriage (Malachi 2:16; Matthew 19:4-6, 9; Hebrews 13:4). Teaching this truth requires endurance to counter worldly views that undermine marital fidelity.</p><p><em>“Let marriage be honorable among all, and let the marriage bed be without defilement.” — Hebrews 13:4</em></p>
        <br><p><strong>Children Obey Your Parents</strong></p><p>Children who respect and obey their parents will succeed, as this pleases Jehovah (Proverbs 1:8, 9; Ephesians 6:1-3). Endurance in teaching this builds strong families grounded in biblical principles.</p><p><em>“Children, be obedient to your parents in union with the Lord, for this is righteous.” — Ephesians 6:1</em></p>
        <br><p><strong>God Has a Name</strong></p><p>God’s name is Jehovah, and true worshipers use it with reverence (Psalm 83:18; Jeremiah 10:10). Enduring in proclaiming His name sets true worship apart from false religions that obscure it.</p><p><em>“May people know that you, whose name is Jehovah, you alone are the Most High over all the earth.” — Psalm 83:18</em></p>
        <br><p><strong>God Communicates Through Scripture</strong></p><p>Jehovah communicates with us through His inspired Word, guiding true worship (2 Timothy 3:16, 17; 2 Peter 1:20, 21). Endurance in studying and teaching the Bible equips people to know Jehovah’s will.</p><p><em>“All Scripture is inspired of God and beneficial for teaching.” — 2 Timothy 3:16</em></p>
        <br><p><strong>God Is Fair and Unbiased</strong></p><p>Jehovah is impartial, accepting all who fear Him and do right (Deuteronomy 10:17; Acts 10:34, 35). Enduring in sharing this truth invites people of all nations to worship the true God.</p><p><em>“God is not partial, but in every nation the man who fears him and does what is right is acceptable to him.” — Acts 10:34, 35</em></p>
        <br><p><strong>God Helps Us</strong></p><p>Jehovah is a refuge, ready to help in times of distress (Psalm 46:1; 145:18, 19). Endurance in teaching this truth comforts those facing trials, pointing them to God’s support.</p><p><em>“God is our refuge and strength, a help that is readily found in times of distress.” — Psalm 46:1</em></p>
        <br><p><strong>Pray to Jehovah</strong></p><p>Jehovah invites us to pray to Him, offering a refuge for our hearts (Psalm 62:8; 65:2; 1 Peter 5:7). Endurance in teaching prayer strengthens faith in Jehovah’s care and guidance.</p><p><em>“Trust in him at all times, O people; pour out your hearts before him.” — Psalm 62:8</em></p>
        <br><p><strong>How to Pray</strong></p><p>The Bible teaches us how to pray meaningfully, as Jesus showed (Matthew 6:7-13; Luke 11:1-4). Enduring in sharing this guidance helps people draw close to Jehovah through proper prayer.</p><p><em>“You must pray, then, this way: ‘Our Father in the heavens, let your name be sanctified.’” — Matthew 6:9</em></p>
        <br><p><strong>Pray Often</strong></p><p>We should pray constantly to stay close to Jehovah (Matthew 7:7, 8; 1 Thessalonians 5:17). Endurance in encouraging frequent prayer builds a strong relationship with God for true worshipers.</p><p><em>“Pray constantly.” — 1 Thessalonians 5:17</em></p>
        <br><p><strong>Jesus’ Teachings Work</strong></p><p>Jesus was a great teacher whose advice always brings success (Matthew 6:14, 15, 34; 7:12). Enduring in sharing his teachings helps people live in harmony with Jehovah’s standards.</p><p><em>“All things, therefore, that you want men to do to you, you also must do to them.” — Matthew 7:12</em></p>
        <br><p><strong>Jesus Foretold Today’s Events</strong></p><p>Jesus prophesied events like wars and preaching that we see today (Matthew 24:3, 7, 8, 14; Luke 21:10, 11). Endurance in proclaiming these fulfilled prophecies prepares people for God’s Kingdom.</p><p><em>“And this good news of the Kingdom will be preached in all the inhabited earth.” — Matthew 24:14</em></p>
        <br><p><strong>Jesus Is God’s Son</strong></p><p>Jesus is the Son of God, not God Almighty, sent to save mankind (Matthew 16:16; John 3:16; 1 John 4:15). Enduring in teaching this truth clarifies Jesus’ role in Jehovah’s purpose.</p><p><em>“You are the Christ, the Son of the living God.” — Matthew 16:16</em></p>
        <br><p><strong>Jesus Is Not God</strong></p><p>Jesus is subordinate to Jehovah, his Father, who is greater (John 14:28; 1 Corinthians 11:3). Endurance in teaching this distinction upholds Jehovah’s sovereignty against false doctrines.</p><p><em>“The Father is greater than I am.” — John 14:28</em></p>
        <br><p><strong>God’s Kingdom Is Real</strong></p><p>God’s Kingdom is a heavenly government that will rule the earth (Daniel 2:44; 7:13, 14; Matthew 6:9, 10; Revelation 11:15). Enduring in preaching this hope inspires faith in Jehovah’s eternal solution.</p><p><em>“The God of heaven will set up a kingdom that will never be destroyed.” — Daniel 2:44</em></p>
        <br><p><strong>Kingdom Replaces Governments</strong></p><p>God’s Kingdom will replace human governments, bringing justice (Psalm 2:7-9; Daniel 2:44). Endurance in sharing this truth counters trust in failing human systems.</p><p><em>“You will break them with an iron scepter, and you will smash them like a piece of pottery.” — Psalm 2:9</em></p>
        <br><p><strong>Kingdom Solves Problems</strong></p><p>God’s Kingdom is the only solution to mankind’s problems, bringing peace and abundance (Psalm 37:10, 11; 46:9; Isaiah 65:21-23). Enduring in this teaching offers hope for a perfect future.</p><p><em>“The meek will possess the earth, and they will find exquisite delight in the abundance of peace.” — Psalm 37:11</em></p>
        <br><p><strong>God Does Not Cause Suffering</strong></p><p>God does not cause suffering; His ways are just (Deuteronomy 32:4; James 1:13). Endurance in teaching this truth comforts those in pain, pointing to Jehovah’s love.</p><p><em>“Perfect is his activity, for all his ways are justice.” — Deuteronomy 32:4</em></p>
        <br><p><strong>Satan Rules This World</strong></p><p>Satan controls this world, causing its woes (Luke 4:5, 6; 1 John 5:19). Enduring in exposing this truth helps people turn to Jehovah for protection.</p><p><em>“The whole world is lying in the power of the wicked one.” — 1 John 5:19</em></p>
        <br><p><strong>God Cares About Suffering</strong></p><p>Jehovah cares deeply about our suffering and promises to help (Psalm 34:17-19; Isaiah 41:10, 13). Endurance in sharing this truth strengthens faith in His compassion.</p><p><em>“Jehovah is close to the brokenhearted; he saves those who are crushed in spirit.” — Psalm 34:18</em></p>
        <br><p><strong>God Will End Suffering</strong></p><p>God will soon end all suffering, creating a new earth (Isaiah 65:17; Revelation 21:3, 4). Enduring in this teaching offers hope for a pain-free future under Jehovah’s rule.</p><p><em>“He will wipe out every tear from their eyes, and death will be no more.” — Revelation 21:4</em></p>
        <br><p><strong>Dead Are Unconscious</strong></p><p>The dead are unconscious, not suffering in any form (Ecclesiastes 9:5; John 11:11-14). Endurance in teaching this biblical truth counters false afterlife beliefs.</p><p><em>“The dead know nothing at all.” — Ecclesiastes 9:5</em></p>
        <br><p><strong>Dead Cannot Help or Harm</strong></p><p>The dead have no power to help or harm the living (Psalm 146:4; Ecclesiastes 9:6, 10). Enduring in this teaching frees people from false fears and superstitions.</p><p><em>“His spirit goes out, he returns to the ground; on that very day his thoughts perish.” — Psalm 146:4</em></p>
        <br><p><strong>Resurrection of Loved Ones</strong></p><p>Dead loved ones will be resurrected to life by Jehovah (Job 14:13-15; John 5:28, 29; Acts 24:15). Endurance in sharing this hope comforts those grieving and builds faith.</p><p><em>“The hour is coming in which all those in the memorial tombs will hear his voice and come out.” — John 5:28, 29</em></p>
        <br><p><strong>Death Will End</strong></p><p>Death itself will be eliminated under God’s Kingdom (Revelation 21:3, 4; Isaiah 25:8). Enduring in teaching this promise inspires hope for eternal life.</p><p><em>“He will swallow up death forever.” — Isaiah 25:8</em></p>
        <br><p><strong>Not All Religions Please God</strong></p><p>Not all religions are acceptable to Jehovah; only true worship pleases Him (Jeremiah 7:11; Matthew 7:13, 14, 21-23). Endurance in teaching this truth guides people to pure worship.</p><p><em>“Not everyone saying to me, ‘Lord, Lord,’ will enter into the Kingdom of the heavens.” — Matthew 7:21</em></p>
        <br><p><strong>God Hates Hypocrisy</strong></p><p>Jehovah despises hypocrisy in worship, demanding genuine devotion (Isaiah 29:13; Micah 3:11; Mark 7:6-8). Enduring in exposing false worship helps people seek true faith.</p><p><em>“This people honor me with their lips, but their hearts are far removed from me.” — Isaiah 29:13</em></p>
        <br><p><strong>Love Identifies True Religion</strong></p><p>Genuine love among worshipers marks true religion, as seen in Jehovah’s Witnesses (Micah 4:3; John 13:34, 35). Endurance in teaching this draws people to God’s people.</p><p><em>“By this all will know that you are my disciples—if you have love among yourselves.” — John 13:35</em></p>
    `
},
{
    T: "Faithful",
    S: [
        "Isaiah 43:10 - “You are my witnesses,” declares Jehovah, “my servant whom I have chosen.”"
    ],
    D: `
        <p>Jehovah’s faithful witnesses, from Abel to modern times, shine as treasures, proclaiming His truth with unwavering faith.</p>
        <br><p><strong>Abel, Enoch, Noah: First Witnesses</strong></p><p>The earliest faithful servants, valued as treasures, witnessed for Jehovah’s righteousness in a corrupt world, proclaiming His truth with unwavering faith, as “the righteous will be remembered forever” (Psalm 112:6). Abel offered a sacrifice pleasing to Jehovah, testifying to his faith through obedient worship (Genesis 4:4). His offering, made “by faith,” earned divine approval (Hebrews 11:4). Though murdered by Cain, Abel’s witness endures, as his blood “cries out” for justice (Genesis 4:10). Enoch “walked with God,” boldly prophesying against wickedness (Jude 14-15). His preaching condemned a godless generation, and Jehovah “took him” to spare him death (Genesis 5:24; Hebrews 11:5), affirming his loyalty to divine truth. Noah, a “preacher of righteousness,” built the ark and warned of the Flood for 120 years (2 Peter 2:5; Genesis 6:3). Facing ridicule, he upheld Jehovah’s laws, saving his family through faith (Hebrews 11:7). His witness stands as a testament to obedience.</p><p><em>“By faith Abel offered God a better sacrifice than Cain.” — Hebrews 11:4</em></p>
        <br><p><strong>Abraham, Isaac, Jacob: Patriarchal Witnesses</strong></p><p>The patriarchs, as treasured servants, established Jehovah’s covenant through unwavering faith, proclaiming His promises in a pagan world, as “the righteous will be remembered forever” (Psalm 112:6). Abraham, leaving Ur at Jehovah’s call, journeyed to Canaan, offering sacrifices and declaring Jehovah’s name (Genesis 12:1-4, 7-8). His obedience, tested by nearly sacrificing Isaac, earned him the title “friend of Jehovah” (James 2:23; Hebrews 11:8-10), forging a covenant for all nations. Isaac, trusting Jehovah’s promise, remained in Canaan despite famine, receiving divine confirmation of the covenant (Genesis 26:3-5). His peaceful resolve amid conflict testified to Jehovah’s guidance, as “I am the God of Abraham your father” (Genesis 26:24). Jacob, wrestling with trials, vowed loyalty to Jehovah, erecting altars at Bethel (Genesis 28:13-15; 35:1-3). His 12 sons formed Israel’s tribes, fulfilling Jehovah’s promise to multiply his offspring, as “I am with you” (Genesis 28:15).</p><p><em>“I will be with you.” — Genesis 28:15</em></p>
        <br><p><strong>Moses, Samuel, Jeremiah: Prophetic Witnesses</strong></p><p>Israel’s prophets, as treasured servants, proclaimed Jehovah’s name and laws, guiding His people to true devotion, as “the word of Jehovah endures” (1 Peter 1:25). Moses, raised in Egypt, led Israel from slavery, receiving the Law at Sinai, declaring “Jehovah your God is one Jehovah” (Deuteronomy 6:4). He boldly confronted Pharaoh, proclaiming Jehovah’s name (Exodus 3:15), teaching Israel to worship Him alone (Exodus 20:3). Samuel, as prophet and judge, anointed Saul and David, urging Israel to serve Jehovah exclusively (1 Samuel 12:10-20). His tireless preaching strengthened devotion, as “serve Jehovah with all your heart” (1 Samuel 12:24). Jeremiah warned Judah of Babylon’s judgment, proclaiming “Jehovah is the true God” (Jeremiah 10:10). Imprisoned and mocked, he faithfully rewrote his burned scrolls (Jeremiah 36:32), testifying to Jehovah’s enduring word.</p><p><em>“This is my name forever.” — Exodus 3:15</em></p>
        <br><p><strong>Jesus, Peter, Paul: Apostolic Witnesses</strong></p><p>Jesus and His apostles, as priceless treasures, established Christian witnessing, proclaiming Jehovah’s Kingdom with steadfast faith, as “the truth will set you free” (John 8:32). Jesus declared “I have made your name known” (John 17:26), teaching Jehovah’s purpose through parables and miracles (Matthew 4:17). He preached publicly and house-to-house (Luke 8:1), enduring death on a stake to uphold Jehovah’s sovereignty (Philippians 2:8). Peter, a leading apostle, preached at Pentecost, declaring Jehovah’s resurrection of Jesus (Acts 2:32-36). Imprisoned and beaten, he continued witnessing (Acts 5:42), stating “we must obey God rather than men” (Acts 5:29). Paul, converted from persecutor, traveled thousands of miles, establishing congregations and writing 14 epistles (Acts 9:15). Beheaded under Nero, he proclaimed “Jehovah is my helper” (Hebrews 13:6).</p><p><em>“Go, make disciples of all the nations.” — Matthew 28:19</em></p>
        <br><p><strong>Polycarp, Justin Martyr, Perpetua: Early Martyrs</strong></p><p>Early Christians, like treasured gems, witnessed for Jehovah amid persecution, preserving His truth, as “be faithful even to death” (Revelation 2:10). Polycarp of Smyrna, a disciple of John, refused to honor false gods, declaring, “I am a Christian.” Burned at the stake in 155 CE, his martyrdom upheld Jehovah’s worship, as “the word of Jehovah endures” (1 Peter 1:25). Justin Martyr, a philosopher-turned-Christian, wrote *Apologies* defending Christianity, proclaiming Jehovah as the true God. Beheaded in 165 CE, his testimony strengthened early believers. Perpetua, a young mother, faced wild beasts in Carthage’s arena in 203 CE, declaring Jehovah’s Kingdom. Her courage bolstered Christian resolve.</p><p><em>“The word of our God endures forever.” — Isaiah 40:8</em></p>
        <br><p><strong>Waldensians, Wycliffe, Tyndale: Reformation Translators</strong></p><p>Medieval and Reformation translators, as treasured servants, proclaimed Jehovah’s Word, making it accessible despite opposition, as “those seeking Jehovah will praise him” (Psalm 22:26). Waldensians, led by Peter Waldo in the 12th century, translated vernacular Bibles, sharing Jehovah’s truth with the poor. Persecuted, they hid in the Alps, proclaiming “worship with spirit and truth” (John 4:24). John Wycliffe’s English Bible (1382) gave access to Jehovah’s Word. Declared a heretic, his bones were burned after death, but his translations spread truth, as “Your word is a lamp to my foot” (Psalm 119:105). William Tyndale’s Pentateuch (1530) proclaimed Jehovah’s name (Exodus 6:3). Strangled and burned in 1536, his faith endured, as “the truth will set you free” (John 8:32).</p><p><em>“Your word is truth.” — John 17:17</em></p>
        <br><p><strong>Ainsworth, Grew, Storrs: Truth Seekers</strong></p><p>Early restorers, like precious treasures, proclaimed Jehovah’s truth, preparing the way for modern witnessing, as “Jehovah searches for those loyal to him” (2 Chronicles 16:9). Henry Ainsworth, a Puritan scholar, used “Jehovah” in his Psalms annotations (1612), citing Psalm 83:18. Exiled for his faith, his work spread Jehovah’s name, as “proclaim his name among the peoples” (Psalm 105:1). Henry Grew taught Jehovah’s name and rejected false doctrines in the 1820s, facing opposition. His steadfastness reached many, as “the dead know nothing at all” (Ecclesiastes 9:5). George Storrs taught earthly resurrection through *Six Sermons* in the 1840s. Persecuted, his faith spread Jehovah’s truth, as “the meek will possess the earth” (Psalm 37:11).</p><p><em>“My people will know my name.” — Isaiah 52:6</em></p>
        <br><p><strong>Russell, Rutherford, Knorr: Modern Witnesses</strong></p><p>Modern witnesses, as treasured servants, globalized Jehovah’s truth through faith and sacrifice, as “this good news of the Kingdom will be preached” (Matthew 24:14). Charles Taze Russell, in 1870, formed a Pittsburgh Bible study, launching *Zion’s Watch Tower* (1879) to publish truth. Distributing millions of tracts amid mob violence, he founded the Watch Tower Society (1884), proclaiming Jehovah’s Kingdom, as “You are my witnesses” (Isaiah 43:10). Joseph Franklin Rutherford, succeeding Russell in 1917, faced imprisonment in 1918 for preaching truth. Naming the group Jehovah’s Witnesses in 1931, he spread Jehovah’s name via radio, as “proclaim his name among the peoples” (Psalm 105:1). Nathan H. Knorr, from 1942, trained missionaries through Gilead School (1943), sending them to 240 lands. His leadership expanded preaching, as “Your word is truth” (John 17:17).</p><p><em>“I did not hold back from preaching.” — Acts 20:20</em></p>
    `
}


];
